name: FCM Topic Subscribe

on:
  workflow_dispatch:
    inputs:
      token:
        description: 'FCM Token'
        required: true
        type: string
      topic:
        description: 'Topic to subscribe'
        required: false
        default: 'daily-feed'
        type: string
      unsubscribe:
        description: 'Unsubscribe from topic'
        required: false
        default: false
        type: boolean
  repository_dispatch:
    types: [fcm-subscribe]

jobs:
  subscribe-to-topic:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'
          cache: true
          
      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Set variables from repository_dispatch
        if: github.event_name == 'repository_dispatch'
        run: |
          echo "FCM_TOKEN=${{ github.event.client_payload.token }}" >> $GITHUB_ENV
          echo "FCM_TOPIC=${{ github.event.client_payload.topic || 'daily-feed' }}" >> $GITHUB_ENV
          echo "FCM_UNSUBSCRIBE=${{ github.event.client_payload.unsubscribe || 'false' }}" >> $GITHUB_ENV

      - name: Set variables from workflow_dispatch
        if: github.event_name == 'workflow_dispatch'
        run: |
          echo "FCM_TOKEN=${{ inputs.token }}" >> $GITHUB_ENV
          echo "FCM_TOPIC=${{ inputs.topic || 'daily-feed' }}" >> $GITHUB_ENV
          echo "FCM_UNSUBSCRIBE=${{ inputs.unsubscribe || 'false' }}" >> $GITHUB_ENV

      - name: Subscribe to FCM topic
        if: env.FCM_UNSUBSCRIBE != 'true'
        working-directory: backend
        env:
          FIREBASE_SERVICE_ACCOUNT_KEY: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}
        run: |
          echo "📱 토픽 '${{ env.FCM_TOPIC }}'에 구독 중..."
          go run cmd/fcm-subscribe/main.go \
            --token "${{ env.FCM_TOKEN }}" \
            --topic "${{ env.FCM_TOPIC }}"

      - name: Unsubscribe from FCM topic
        if: env.FCM_UNSUBSCRIBE == 'true'
        working-directory: backend
        env:
          FIREBASE_SERVICE_ACCOUNT_KEY: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}
        run: |
          echo "📱 토픽 '${{ env.FCM_TOPIC }}'에서 구독 해제 중..."
          go run cmd/fcm-subscribe/main.go \
            --token "${{ env.FCM_TOKEN }}" \
            --topic "${{ env.FCM_TOPIC }}" \
            --unsubscribe